/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IdRouteImport } from './routes/$id'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as PlatformsRouteImport } from './routes/platforms'
import { Route as IdentityAccessRouteImport } from './routes/identity/access'
import { Route as IdentityUsersRouteImport } from './routes/identity/users'
import { Route as MigrationHistoryRouteImport } from './routes/migration/history'
import { Route as MigrationImportRouteImport } from './routes/migration/import'
import { Route as MigrationPendingRouteImport } from './routes/migration/pending'
import { Route as MigrationSyncRouteImport } from './routes/migration/sync'
import { Route as PlatformsUsersRouteImport } from './routes/platforms/users'
import { Route as IdentityUsersIdRouteImport } from './routes/identity/users/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IdRoute = IdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformsRoute = PlatformsRouteImport.update({
  id: '/platforms',
  path: '/platforms',
  getParentRoute: () => rootRouteImport,
} as any)
const IdentityAccessRoute = IdentityAccessRouteImport.update({
  id: '/identity/access',
  path: '/identity/access',
  getParentRoute: () => rootRouteImport,
} as any)
const IdentityUsersRoute = IdentityUsersRouteImport.update({
  id: '/identity/users',
  path: '/identity/users',
  getParentRoute: () => rootRouteImport,
} as any)
const MigrationHistoryRoute = MigrationHistoryRouteImport.update({
  id: '/migration/history',
  path: '/migration/history',
  getParentRoute: () => rootRouteImport,
} as any)
const MigrationImportRoute = MigrationImportRouteImport.update({
  id: '/migration/import',
  path: '/migration/import',
  getParentRoute: () => rootRouteImport,
} as any)
const MigrationPendingRoute = MigrationPendingRouteImport.update({
  id: '/migration/pending',
  path: '/migration/pending',
  getParentRoute: () => rootRouteImport,
} as any)
const MigrationSyncRoute = MigrationSyncRouteImport.update({
  id: '/migration/sync',
  path: '/migration/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformsUsersRoute = PlatformsUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => PlatformsRoute,
} as any)
const IdentityUsersIdRoute = IdentityUsersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => IdentityUsersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$id': typeof IdRoute
  '/logs': typeof LogsRoute
  '/platforms': typeof PlatformsRouteWithChildren
  '/identity/access': typeof IdentityAccessRoute
  '/identity/users': typeof IdentityUsersRouteWithChildren
  '/migration/history': typeof MigrationHistoryRoute
  '/migration/import': typeof MigrationImportRoute
  '/migration/pending': typeof MigrationPendingRoute
  '/migration/sync': typeof MigrationSyncRoute
  '/platforms/users': typeof PlatformsUsersRoute
  '/identity/users/$id': typeof IdentityUsersIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$id': typeof IdRoute
  '/logs': typeof LogsRoute
  '/platforms': typeof PlatformsRouteWithChildren
  '/identity/access': typeof IdentityAccessRoute
  '/identity/users': typeof IdentityUsersRouteWithChildren
  '/migration/history': typeof MigrationHistoryRoute
  '/migration/import': typeof MigrationImportRoute
  '/migration/pending': typeof MigrationPendingRoute
  '/migration/sync': typeof MigrationSyncRoute
  '/platforms/users': typeof PlatformsUsersRoute
  '/identity/users/$id': typeof IdentityUsersIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$id': typeof IdRoute
  '/logs': typeof LogsRoute
  '/platforms': typeof PlatformsRouteWithChildren
  '/identity/access': typeof IdentityAccessRoute
  '/identity/users': typeof IdentityUsersRouteWithChildren
  '/migration/history': typeof MigrationHistoryRoute
  '/migration/import': typeof MigrationImportRoute
  '/migration/pending': typeof MigrationPendingRoute
  '/migration/sync': typeof MigrationSyncRoute
  '/platforms/users': typeof PlatformsUsersRoute
  '/identity/users/$id': typeof IdentityUsersIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$id'
    | '/logs'
    | '/platforms'
    | '/identity/access'
    | '/identity/users'
    | '/migration/history'
    | '/migration/import'
    | '/migration/pending'
    | '/migration/sync'
    | '/platforms/users'
    | '/identity/users/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$id'
    | '/logs'
    | '/platforms'
    | '/identity/access'
    | '/identity/users'
    | '/migration/history'
    | '/migration/import'
    | '/migration/pending'
    | '/migration/sync'
    | '/platforms/users'
    | '/identity/users/$id'
  id:
    | '__root__'
    | '/'
    | '/$id'
    | '/logs'
    | '/platforms'
    | '/identity/access'
    | '/identity/users'
    | '/migration/history'
    | '/migration/import'
    | '/migration/pending'
    | '/migration/sync'
    | '/platforms/users'
    | '/identity/users/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IdRoute: typeof IdRoute
  LogsRoute: typeof LogsRoute
  PlatformsRoute: typeof PlatformsRouteWithChildren
  IdentityAccessRoute: typeof IdentityAccessRoute
  IdentityUsersRoute: typeof IdentityUsersRouteWithChildren
  MigrationHistoryRoute: typeof MigrationHistoryRoute
  MigrationImportRoute: typeof MigrationImportRoute
  MigrationPendingRoute: typeof MigrationPendingRoute
  MigrationSyncRoute: typeof MigrationSyncRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$id': {
      id: '/$id'
      path: '/$id'
      fullPath: '/$id'
      preLoaderRoute: typeof IdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platforms': {
      id: '/platforms'
      path: '/platforms'
      fullPath: '/platforms'
      preLoaderRoute: typeof PlatformsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/identity/access': {
      id: '/identity/access'
      path: '/identity/access'
      fullPath: '/identity/access'
      preLoaderRoute: typeof IdentityAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/identity/users': {
      id: '/identity/users'
      path: '/identity/users'
      fullPath: '/identity/users'
      preLoaderRoute: typeof IdentityUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/migration/history': {
      id: '/migration/history'
      path: '/migration/history'
      fullPath: '/migration/history'
      preLoaderRoute: typeof MigrationHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/migration/import': {
      id: '/migration/import'
      path: '/migration/import'
      fullPath: '/migration/import'
      preLoaderRoute: typeof MigrationImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/migration/pending': {
      id: '/migration/pending'
      path: '/migration/pending'
      fullPath: '/migration/pending'
      preLoaderRoute: typeof MigrationPendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/migration/sync': {
      id: '/migration/sync'
      path: '/migration/sync'
      fullPath: '/migration/sync'
      preLoaderRoute: typeof MigrationSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platforms/users': {
      id: '/platforms/users'
      path: '/users'
      fullPath: '/platforms/users'
      preLoaderRoute: typeof PlatformsUsersRouteImport
      parentRoute: typeof PlatformsRoute
    }
    '/identity/users/$id': {
      id: '/identity/users/$id'
      path: '/$id'
      fullPath: '/identity/users/$id'
      preLoaderRoute: typeof IdentityUsersIdRouteImport
      parentRoute: typeof IdentityUsersRoute
    }
  }
}

interface PlatformsRouteChildren {
  PlatformsUsersRoute: typeof PlatformsUsersRoute
}

const PlatformsRouteChildren: PlatformsRouteChildren = {
  PlatformsUsersRoute: PlatformsUsersRoute,
}

const PlatformsRouteWithChildren = PlatformsRoute._addFileChildren(
  PlatformsRouteChildren,
)

interface IdentityUsersRouteChildren {
  IdentityUsersIdRoute: typeof IdentityUsersIdRoute
}

const IdentityUsersRouteChildren: IdentityUsersRouteChildren = {
  IdentityUsersIdRoute: IdentityUsersIdRoute,
}

const IdentityUsersRouteWithChildren = IdentityUsersRoute._addFileChildren(
  IdentityUsersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IdRoute: IdRoute,
  LogsRoute: LogsRoute,
  PlatformsRoute: PlatformsRouteWithChildren,
  IdentityAccessRoute: IdentityAccessRoute,
  IdentityUsersRoute: IdentityUsersRouteWithChildren,
  MigrationHistoryRoute: MigrationHistoryRoute,
  MigrationImportRoute: MigrationImportRoute,
  MigrationPendingRoute: MigrationPendingRoute,
  MigrationSyncRoute: MigrationSyncRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
